on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Install dependencies'
        run: sudo apt-get update && sudo apt-get install -y cargo
      - name: 'Run tests'
        run: cargo test
